#                                                                 SoftMsg file
#
#  deflog.msg
# The default privs for log files...
# Possiblities are ad, la and su.
# (note, if you change any of these and the log
#  file exists...it wont do anything, these are
#  only there as a default for when the file doesnt
#  exists and is created...)
#

sneeze:		su
drag:		su
rm_shout:	su
rm_sing:	su
resident:	su
nuke:		su
dumb:		su
yoyo:		su
git:		su
ask:		su
marry:		su
msg:		su
warn:		su
jail:		su
prs:		su
item_delete:	su
pennies:	su
builder:	su
minister:	su
spam:		su
forcehelp:	su
social:		su
caps:		su
blanks:		su
newconn:	su
idle:		su
timeouts:	su
site:		su
session:	su
reportto:	su
idea:		su
bug:		su

rm_move:	la
forever:	la
error:		la
grant:		la
remove:		la
suicide:	la
banish:		la
duty:		la
shutdown:	la
boot:		la
chlim:		la
newbies:	la
recover:	la
item_grant:	la
verbose:	la
news:		la
sufailpass:	la
robot:		la
rename:		la
validate_email:	la
assist:		la
adnews:		la
angel:		la
sync:		la
dump:		la
ident:		la
intercom:	la
mail:		la
su:		la
connection:	la


commands:	ad
logs:		ad
ressies:	ad
lag:		ad
wall:		ad
edit:		ad
bump:		ad
channel:	ad
make:		ad
edtime:		ad
sigpipe:	ad
stack:		ad
help:		ad
reply:		ad
