#                                                                 SoftMsg file
#
#   frogs.msg
#  This is the file that contains the messages to show for
#  frogged ppls....instead of the communication stuff they input
#

say:		I want my rattle fixed.
shout:		I want my rattle fixed!!!
tell:		I want you to fix my rattle.

emote:		shakes a broken rattle
remote:		shakes a broken rattle.
yemote:         shakes a broken rattle   *sniff*

think:		Ahhhhh, a shiny new rattle ...
ythink:		Ahhhhh, a shiny new rattle ...

echo:		[Rattle] [Rattle] [Rattle]
recho:		[Rattle] [Rattle] [Rattle]
yecho:		[Rattle] [Rattle] [Rattle]

sing:		I got the broken rattle blueeeeeeeeeees
rsing:		I got the broken rattle blueeeeeeeeeees
ysing:		I got the broken rattle blueeeeeeeeeees

whisper:	Psst!  Fix my rattle!
exclude:	Someone puhlease fix my rattle!

yell:		Gimme a new rattle !!

