#                                                                 SoftMsg file
#
# pdefaults.msg
# These are the newbie default stuffs that are set on login
#
title:		the newbie so treat me nicely.
description:	I've yet to figure out the description command.
plan:		I have no plans at all.
enter_msg:	enters in a standard kind of way.
logonmsg:	appears suddenly.
logoffmsg:	leaves quietly.

prompt:		PG+>
cprompt:	(con)->

colorset:	HYBGAaCPNR

# the rest should always be numbers
max_rooms:	2
max_exits:	5
max_autos:	5
max_list:	25
max_mail:	10
max_alias:	10

money:		50

no_shout:	180
no_sing:	180

term_width:	79
word_wrap:	10

