#                                                                 SoftMsg file
#     rooms.msg
#  where we find strings and defaults relating to rooms
#

#
# Default room name, needs exactly one %s where name is placed
#
def_name:	in %s's bed.

#
# Default room entermsg, needs exactly one %s where name is placed
#
def_entermsg:	goes to sleep in %s's room.

#
# Default room desc, needs exactly one %s where name is placed
#
def_desc:	
	   A small but cozy bedroom belonging to %s.
	   Don't you think you should give it a better description?
	

#
# Strings shown on 'look' for how many ppl are in the room
#  (multiple_here needs exactly one %s where the word count
#   of how many ppl are substituted)
#

noone_here:	
	
	There is nobody here but you ...
	

one_here:	
	
	There is only one other person here ...
	

multiple_here:	
	
	There are %s other people here ...
	


#
# This is the message shown to the room from which a player is grabbed
#  (needs exactly one %s where the name is substitued)
#
grabbed_from:	A hand reaches down from the sky and grabs %s ...

#
# This is the message down to the room a player is pulled into
#  (needs exactly one %s where the name is substitued)
#
grabbed_to:	%s spins rapidly into being ...

#
# This is the message seen by someone that is grabbed
#  (needs exactly one %s where the grabber's name is substitued)
#
got_grabbed:	%s stretches out and grabs you !!!!!!

#
# This is the message seen by someone when they grab another
#  (needs exactly one %s where the person grabbed name is put)
did_grab:	You successfully grab %s.


#
# The message seen by those in a room when a player bounces
#  (needs exactly one %s where the persons name is substutited)
#
bounce_msg:	%s spins around and bounces into the air !!


#
# The message shown when someone tries to move, but has no_move
#
cant_move:	You seem to be stuck to the ground.

