#                                                                 SoftMsg file
#   session.msg
#  messages for the session stuffs....
#

# This is the default session, that is the session that is set on boot
default_session:	I beg of you... set me.

# This is the default setter of the default session
default_setter:		No-one

# This is the time (in mins) ppl must wait before session changes
# (it must be a number)
session_reset_time:	15

