#                                                                 SoftMsg file
#
#   shutdowns.msg
#  messages for those strings seen on shutdown
#  (you can leave any of these out if you so wish)
#

1day:	-=*> Reboot, tommorrow, this time, be there or be square...      <*=-

15mins:	-=*> Reboot in 15 mins, most people can have sex in less time... <*=-

10mins:	-=*> Reboot in 10 mins, Speedy Gonzalez waves to you. Arriva ;-) <*=-

5mins:	-=*> Reboot in 5 mins, there's plenty of time to edit your list. <*=-

3mins:	-=*> Reboot in 3 mins, last chance to talk silly admins outta it <*=-

2mins:	-=*> Reboot in 2 mins, so the three ring circus will be closing. <*=-

1min:	-=*> Reboot in 1 minute, we'll be right back up.. (we hope...)   <*=-

45secs:	-=*> Reboot in 45 secs, (this space for rent - call 18009110000) <*=-

30secs:	-=*> Reboot in 30 secs, Watch all the people start loggingoff..  <*=-

15secs:	-=*> Reboot in 15 secs, We should be back up in 30 seconds or so <*=-

10secs:	-=*> Reboot in 10 secs, Initiating final liftoff sequence now... <*=-

9secs:	-=*> Reboot in 9

8secs:	-=*>           8

7secs:	-=*>           7

6secs:	-=*>           6

5secs:	-=*>           5

4secs:	-=*>           4

3secs:	-=*>           3

2secs:	-=*>           2

1secs:	-=*>           1
