----------------------------- Colour Test ---------------------------------
	If you can see ^Hfingerpainting^N then you can join in
        viewing the ^Rr^Ba^yi^Cn^Hb^Yo^Pw^N of colors of fingerpaint that
	     we have made available on this program. 

 ^Rbright red^N  ..  ^^R  ^Yyellow^N        ..  ^^Y  ^Bbright blue^N ..  ^^B 
 ^rdark red^N    ..  ^^r  ^ybrown^N         ..  ^^y  ^bdark blue^N   ..  ^^b 
 ^Alight gray^N  ..  ^^A  ^pdark purple^N   ..  ^^p  ^Hwhite^N       ..  ^^H
 ^adark gray^N   ..  ^^a  ^Pbright purple^N ..  ^^P  ^IInverse^N     ..  ^^I
 ^Cbright cyan^N ..  ^^C  ^Gbright green^N  ..  ^^G  ^Kblink text^N  ..  ^^K 
 ^cdark cyan^N   ..  ^^c  ^gdark green^N    ..  ^^g  ^UUnderline^N   ..  ^^U 
 ^Ncolors off^N  ..  ^^N                        ^SItalic^N      ..  ^^S

By the way, the ^^ means you LITERALLY type <shift><6>, ^K^RNOT <control>^N

Of course, not EVERYONE will be able to view this correctly.  If you don't 
see colors, and instead see a mess, then don't turn colors on. Not a lot 
can be done if it doesn't work.  But if it ^Ydoes^N work, you can turn 
fingerpaint on by typing ^Hcolor^N
---------------------------------------------------------------------------
