           _______ __                                             __ 
          |       |  |---.-.--.--.-----.----.-----.--.--.-----.--|  |
          |   -   |  |  _  |  |  |  _  |   _|  _  |  |  |     |  _  |
          |   ____|__|___._|___  |___  |__| |_____|_____|__|__|_____|  /
          |   |            |_____|_____|                     .        / 
          |   |                                          _  /   _    /
          `---' A stable and bug free version           /_)/(_(/_)  o
                  of PG 96 with additional features! . /                       
                                                    (_/          
                
                 Written by Silver, phypor and blimey and based
                      upon Elsewhere-Too by Simon Marsh.


