
  Greetings from us at <<setme>>
  ------------------------------

  This is an automatically sent email to you whenever you set or
  change your email address, so there is no need to reply.

  If you have any questions or concerns, or if you have no idea
  why this message is coming to you, please reply to it directly.

  Thanks for your visit and we hope you have many more in the future.

                                                    ~the admin


