
------------------------------- Hitells -----------------------------------
Hitells are an easy way to differentiate in-room actions from person
                       to person communication.    

vt100   : Probably best for a computer lab. 
ansi    : Possibly best if you're dialing in, or on a good machine
vt102   : Basically the same as vt100, only minor differences.
vt220   : Even better than vt100 and vt102 but requires newer terminal 
sun     : For a sun workstation.
xterm   : For someone running xwindows
adm     : Specific termial type that isn't very common  
hp2392  : Specific termial type that isn't very common  
wyse-30 : Specific termial type that isn't very common 
tvi912  : Specific termial type that isn't very common  

If you're unsure, try vt100 -- this seems to work for the most people.
Once on the program, you can change this setting with the HITELLS command
---------------------------------------------------------------------------

