
---------------------- Information for New Users --------------------------

&t is a Playground Plus (by Silver) chat program based
around Playground96 (by traP, astyanax, Nogard and vallie) which itself is
based around Summink (by Athanasius) which itself is based on EW-Too by
Simon Marsh.

It is here for one and all as a place to just relax and chat.

Look around and enjoy yourself. If you find that you like it
and would like a Permanent Account, then just ask one
of our SuperUsers for "Residency".  If you don't know who they are,
just ask another user, or type 'lsu'.  If you need information on
how to use &t, just type "help" once you are online.

If you have any problems then email the admins at &e

---------------------------------------------------------------------------

