


---------------------------------------------------------------------------

  Sorry but &t is currently barring new people from your site.

  This could be temporary (due to a spammer) or perminant. We suggest you
  try again in about 10 minutes and if this site is still barred then
  you will need to email the admin at &e to register a
  character.

  To register, you will need to send a name, email address and password
  (The password should be changed as soon as you log on).

---------------------------------------------------------------------------
