
--------------------------------- Welcome --------------------------------

   &t is here for one and all as a place to relax and chat.
The aim of the program is simply to provide a nice, secure environment
 in which you can talk. Nice, because it has a multitude of features
to make life easier, and secure because we guarentee that anything you
  do in private cannot be snooped or intercepted by anybody but the
                   people you intended to talk to.
It is usual if you wish to use the program on a regular basis to get
'residency'. This means you can use some of the more advanced features
 of the program, and that you get all your information saved between
    visits. It also means you get a password associated with your
character name so that no-one else can use it. To get residency it is
usually sufficient to just ask around, and there will probably be a
                   'superuser' on who can help you.
     Once in the program, the best thing to do is type 'help' and
'help index' so that you can see the sort of help that is available,
                    and then carry on from there.

-------------------------------------------------------------------------
