------------------------------- The Rules --------------------------------

  This is a set of guidelines of expected behaviour on the program.

   What you do on your own is private, but, should anything you do
 be abusive or annoying to other characters, then be prepared to bear
 the full brunt of the consequences. This may involve anything deemed
   suitable by the administrators or superusers including complete
       banishment from the program and/or 'real life' actions.

  Multiple characters are frowned upon, all you are doing is simply
     wasting disk space. Any person who is found to have multiple
   residencies risks having ALL their characters brutally removed.

  The actions of any administrator or superuser are beyond argument.

 By entering the program, you are explicitly accepting these guides.
 Having read all this, please remember that the aim of the program is
                      simply to relax and enjoy.

-------------------------------------------------------------------------
