--------------------- SuperUser Message of the Day ------------------------

  We are running the Playground+ base code.

  If you have experience with PG96 talkers then you'll find this more
  pleasant to use. If not then hopefully you'll love it!!

  If you can't help the residents with any of their questions then please
  get them to send an email to &e.

---------------------------------------------------------------------------
